pipeline {
  agent {
     node { 
        label 'testlabel'
        } 
  }
  stages {
    stage('Checkout Scm') {
      steps {
        git(url: "${gitUrl}", credentialsId: "${gitCredentialID}")
      }
    }
    }

  options {
    buildBlocker(useBuildBlocker: false, blockLevel: 'GLOBAL', scanQueueFor: 'DISABLED')
  }
  triggers {
    pollSCM('* * * * *')
  }
}
