library '_github.com_pipeline-demo-caternberg_pipeline_examples' _
def mavenPod = libraryResource 'podtemplates/podTemplate-maven.yaml'
// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            //#deprectatedlabel 'mavenPod'
            defaultContainer "maven"
            yaml mavenPod
        }
    }
    stages {
        stage('Hello') {
            steps {
                sh 'hostname'
                echo "DAS IST EIN UPDATE"
                helloWorld "${firstname}"
            }
        }
        stage('Hello 2') {
            steps {
                sh 'hostname'
                helloWorld "${firstname}"
            }
        }
          stage('Hello 3') {
                    steps {
                        sh 'hostname'
                        helloWorld "${firstname}"
                    }
                }
    }
}
