library '_github.com_pipeline-demo-caternberg_pipeline_examples' _
def agentPod = libraryResource 'podtemplates/podTemplate-curl.yaml'
def testName="TESTNAME"
// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            //#deprectatedlabel 'mavenPod'
            defaultContainer "custom-agent"
            yaml agentPod
        }
    }
    stages {
        stage('Hello') {
            steps {
                sh 'hostname'
                helloWorld "${firstname}"
                helloWorld "${testName}"
            }
        }
        stage('Hello 2') {
            steps {
                sh 'hostname'
                helloWorld "${firstname}"
            }
        }
    }
}
