//see https://stackoverflow.com/questions/57261787/use-object-returned-by-readyaml-from-file-in-declarative-jenkinsfile
def loadValuesYaml() {
    def valuesYaml = readYaml(file: './ci.yaml')
    return valuesYaml
}

def getYamlValue(x) {
    return loadValuesYaml()[x]
}

def execCustomSteps(stageName) {
        loadValuesYaml().stage.each { stage ->
        echo "stage.nane: $stage.name, stageName: ${stageName}"
        if ("$stage.name" == "${stageName}") {
            stage.steps.each { step ->
                echo step.name
                echo step.exec
                evaluate(step.exec)
            }
            return null;
        }
    }
}

pipeline {
    agent {
        kubernetes {
            defaultContainer "maven"
            yaml """
             kind: Pod
             metadata:
               name: cloudbees-core-agent
             spec:
               containers:
                 - name: maven
                   image: maven:3.9.5-eclipse-temurin-17-alpine
                   runAsUser: 1000
                   command:
                     - cat
                   tty: true
                   workingDir: "/home/jenkins/agent"
             """
        }
    }
    stages {
        stage('Init') {
            steps {
                script {
                    //Load config
                    valuesYaml = loadValuesYaml()
                    //println valuesYaml.getClass()

                    //generate properties, global options and parameters
                    //see https://docs.cloudbees.com/docs/cloudbees-ci/latest/automating-with-jenkinsfile/customizing-parameters
                    evaluate(valuesYaml.properties)

                    //generate global environment vars
                    env.APP_NAME = getYamlValue("appName")
                    loadValuesYaml().environment.each { environmentVar ->
                        evaluate("env."+environmentVar)
                    }
                    /**
                     * Examples on how to access values from yamlConfig
                     * */
                    //Example1
                    echo valuesYaml.appName
                    //Example2
                    echo getYamlValue("appName")
                    //Example3 use env vars
                    sh "echo ${env.APP_NAME}"
                    echo "ENV VAR EXAMPLE_KEY1 FROM yaml file: ${env.EXAMPLE_KEY1}"
                    echo "ENV VAR EXAMPLE_KEY2 FROM yaml file: ${env.EXAMPLE_KEY2}"
                    echo "PARAM BOOL1: ${params.bool1}"
                }
            }
        }

        stage('ReadAndExecSteps') {
            steps {
                //Execute custom steps
                //execCommonSteps("build")

                //Execute custom steps
                execCustomSteps("build")

                //Example3 use env vars
                sh "echo ${env.APP_NAME}"
                echo "ENV VAR EXAMPLE_KEY1 FROM yaml file: ${env.EXAMPLE_KEY1}"
                echo "ENV VAR EXAMPLE_KEY2 FROM yaml file: ${env.EXAMPLE_KEY2}"
                echo "PARAM BOOL2: ${params.bool2}"
            }
        }
    }
}